name: Deploy to staging env
on:
  release:
    types: [prereleased]
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_STAGING_PROJECT_ID }}
jobs:
  smart-contracts:
    name: "Smart Contracts"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build & Test
        uses: ./.github/actions/smart-contracts
  dApp:
    name: dApp
    runs-on: ubuntu-latest
    needs: smart-contracts
    steps:
      - uses: actions/checkout@v3
      - name: Build dApp
        uses: ./.github/actions/dapp
        with:
          environment: staging
          
      # Install the latest Vercel CLI.
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      # Pull the Vercel environment configuration for the preview (staging) environment.
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      # Build your project artifacts.
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      # Deploy the prebuilt artifacts to Vercel.
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
