name: Deploy to staging env
on:
  release:
    types: [prereleased]
jobs:
  smart-contracts:
    name: "Smart Contracts"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build & Test
        uses: ./.github/actions/smart-contracts
  dApp:
    name: dApp
    runs-on: ubuntu-latest
    needs: smart-contracts
    steps:
      - uses: actions/checkout@v3
      - name: Build dApp
        uses: ./.github/actions/dapp
        with:
          environment: staging
      - name: Deploy to wban-testing.banano.cc
        uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_UNIVERSAL_TESTING_DAPP_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Staging deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: frontend/dist
